image: python:3.6-slim

stages:
  - test
  - build

before_script:
  - export PIP_CACHE_DIR="pip-cache"
  - pip install -r requirements-travis.txt

cache:
  paths:
    - pip-cache

test:
  stage: test
  script:
  - set -e
  - python setup.py test
  artifacts:
    paths:
      - tests/report.xml

build:
  stage: build
  script:
  - python setup.py bdist_wheel sdist
  artifacts:
    paths:
      - dist/
