image: python:3.6-slim

stages:
  - test
  - build
before_script:
  - export PIP_CACHE_DIR="pip-cache"
  - pip install -r requirements-travis.txt
cache:
  paths:
    - pip-cache
lint:
  stage: test
  script:
    - python setup.py flake8
pytest:
  stage: test
  script:
  - set -e
  - python setup.py test
  artifacts:
    reports:
      junit: pytest_report.xml


build:
  stage: build
  script:
  - python setup.py bdist_wheel sdist
  artifacts:
    paths:
      - dist/
