language: python
python:
- '3.7'
os: linux
branches:
  only:
  - develop
  - master
install:
- pip install -r requirements-travis.txt
script:
- set -e
- python setup.py test
deploy:
- provider: pypi
  username: __token__
  password:
    secure: "srA5Jf0jmv4eyzwGOlPF5rHU0CdPyT6uCqgAwqxjYztNvIevyWtqdb8bBUsS1cTqsEP3XBVcoz0Fzqwd6HtpOAO8shhq8/62v42frOua7tfFHH4eXjXWQj4gW8bNHjvz6+EAlEVzwaM+N582vpFEjsm/p2Z6dvIFTAvc5PUgOvhONPekWpUaniJMMBGqluK/OC9ypJwV611qOp6tjEsT0gn9ux7e0gJdVyFJHGffyyt9yLsmnmQzQ5LLf+lr6N9L4MtpJwkYHH6C96uIgm1l9oirywWO9KyaF/+PJAHVXSUW8N5NhgB6dFYHuUbhFsk8m5doCfNiOuKq8fbnriAoCEIOG27Y/FQY4XMK6YTG7/A6XMmVVczV+RO0R7w0m1E5FMlOiA2aZhySrx9i1NZs+30SCFHA7Zr/0C7ESyDbNVKSUPjLQapuHVuwypTpCymhwcOF54PQeuyZ0HRV1W09MZJpB9YqqmTLF2l5bo+EsAq0uefVaOx5Re7sZKzByDwEL3hQoO1eJlFiZACg6iG48eCTSo20MkpwDIWCaX0E/9PT0Pwqq1fSScmHISxCpzSt9f5OSvu4m3xJdRvYLaWFw5r0xBRkN3HVm6OCITBW93vd8GTXMrXf4skNn5zpYn/diJ42HqRbw3JbC7wo6jtZRyT4b9jcDYuwrJjNIbwvw3o="
  distributions: sdist bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true
after_script:
- echo "Deploy to PyPI finished."
